- name: Test GoatCounter API
  env:
    GOATCOUNTER_API_KEY: ${{ secrets.GOATCOUNTER_API_KEY }}
  run: |
    curl --fail \
      -u ":$GOATCOUNTER_API_KEY" \
      -H "Content-Type: application/json" \
      https://ciphercook.goatcounter.com/api/v0/stats/total